import { StyleSheet, Platform } from "react-native";
import { width, ps } from "./constants";

const isTablet = width >= 600;
const bookCardWidth = (width - 30) / 2;
const featureImageSize = isTablet ? 160 : width * 0.32;
const GM_CARD_W = width - 32;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fcfcfc",
    marginBottom: 0,
  },
  scrollView: {
    flex: 1,
  },
  // ── Arriving Soon ──
  arrivingSection: {
    backgroundColor: "#FFF4E9",
    marginHorizontal: 12,
    marginTop: 16,
    borderRadius: 16,
    overflow: "hidden",
    padding: 18,
  },
  arrivingContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  arrivingTextCol: {
    width: "60%",
    paddingRight: 8,
  },
  arrivingLottieCol: {
    width: "40%",
    alignItems: "center",
    justifyContent: "center",
  },
  arrivingLottie: {
    width: "140%",
    aspectRatio: 847 / 491,
  },
  arrivingTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#452300",
    lineHeight: 28,
    marginBottom: 8,
  },
  arrivingSub: {
    fontSize: 12,
    color: "#A25100",
    lineHeight: 19,
  },
  arrivingBtn: {
    backgroundColor: "#FFD9B3",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    alignItems: "center",
    marginTop: 14,
  },
  arrivingBtnText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#3B1A00",
    textAlign: "center",
  },
  gymRequestTooltip: {
    marginTop: 8,
    backgroundColor: "#1A1A1A",
    borderRadius: 8,
    paddingVertical: 7,
    paddingHorizontal: 12,
    alignSelf: "center",
  },
  gymRequestTooltipText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "500",
    textAlign: "center",
  },
  arrivingHelpText: {
    fontSize: 13,
    color: "#3B1A00",
    textDecorationLine: "underline",
    textAlign: "center",
  },
  // ── Fitness Classes Banner First (screenshot-matched) ──
  fitnessClassBannerFirst: {
    flexDirection: "row",
    backgroundColor: "#C7DAFF",
    marginBottom: 4,
    overflow: "hidden",
    minHeight: 110,
    alignItems: "center",
  },
  fitnessClassBannerLeft: {
    flex: 1,
    paddingVertical: 18,
    paddingLeft: 18,
    paddingRight: 8,
    justifyContent: "center",
  },
  fitnessClassBannerTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#0e2b65",
    marginBottom: 4,
    letterSpacing: -0.3,
  },
  fitnessClassBannerSub: {
    fontSize: 12,
    fontWeight: "500",
    color: "#0e2b65",
    lineHeight: 17,
    marginBottom: 12,
  },
  fitnessClassBannerPricePill: {
    alignSelf: "flex-start",
    backgroundColor: "#ffffff",
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderColor: "#4A5BA8",
    borderWidth: 1,
  },
  fitnessClassBannerPriceText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#4A5BA8",
  },
  fitnessClassBannerImageWrap: {
    width: 170,
    alignSelf: "stretch",
    overflow: "hidden",
    position: "relative",
  },
  // ── Fitness Classes Banner (below location header) ──
  fitnessClassBanner: {
    alignItems: "center",
    paddingBottom: 14,
    height: 170,
    position: "relative",
  },
  fitnessClassBannerScanner: {
    alignItems: "center",
    paddingBottom: 14,
    height: 135,
    position: "relative",
  },
  fitnessClassPricePill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#4A5BA8",
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 20,
    gap: 8,
  },
  fitnessClassPriceAmount: {
    fontSize: 36,
    fontWeight: "900",
    color: "#ffffff",
    letterSpacing: -1,
  },
  fitnessClassPriceLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: "#ffffff",
    lineHeight: 18,
    fontStyle: "italic",
  },
  fitnessClassBannerText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#3D3F69",
    textAlign: "center",
    position: "absolute",
    bottom: 40,
  },
  // ── First-Time Welcome Credits Banner ──
  welcomeCreditCard: {
    marginHorizontal: 12,
    marginTop: 12,
    marginBottom: 4,
    borderRadius: 18,
    elevation: 6,
    shadowColor: "#1364D7",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    overflow: Platform.OS === "android" ? "hidden" : "visible",
  },
  welcomeCreditCardBooking: {
    marginHorizontal: 12,
    marginTop: 12,
    marginBottom: 4,
    borderRadius: 18,
    overflow: Platform.OS === "android" ? "hidden" : "visible",
  },
  welcomeCreditGradient: {
    borderRadius: 18,
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 18,
    overflow: "hidden",
  },
  welcomeCreditClose: {
    position: "absolute",
    top: 10,
    right: 12,
    zIndex: 10,
    backgroundColor: "rgba(255,255,255,0.15)",
    borderRadius: 20,
    padding: 4,
  },
  welcomeCreditTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 8,
  },
  welcomeCreditSparkle: {
    fontSize: 14,
  },
  welcomeCreditTag: {
    fontSize: 11,
    fontWeight: "700",
    color: "rgba(255,255,255,0.85)",
    letterSpacing: 1.2,
    textTransform: "uppercase",
    backgroundColor: "rgba(255,255,255,0.15)",
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 20,
    overflow: "hidden",
  },
  welcomeCreditTagBooking: {
    fontSize: 11,
    fontWeight: "700",
    color: "rgba(255,255,255,0.85)",
    letterSpacing: 1.2,
    textTransform: "uppercase",
    backgroundColor: "rgba(255, 255, 255, 0.62)",
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 20,
    overflow: "hidden",
  },
  welcomeCreditTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#ffffff",
    marginBottom: 8,
    lineHeight: 26,
    letterSpacing: -0.3,
  },
  welcomeCreditHighlight: {
    color: "#FFD700",
    fontWeight: "900",
  },
  welcomeCreditSub: {
    fontSize: 13,
    color: "rgba(255,255,255,0.85)",
    lineHeight: 19,
    marginBottom: 16,
  },
  welcomeCreditPill: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#ffffff",
    borderRadius: 24,
    paddingVertical: 8,
    paddingHorizontal: 16,
    gap: 6,
  },
  welcomeCreditPillText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#1364D7",
  },
  // ── New AI Credits Banner ──
  aiCreditsWrapper: {
    marginHorizontal: 12,
    marginTop: ps(10),
    marginBottom: ps(4),
    position: "relative",
  },
  aiCreditsCard: {
    height: ps(110),
    borderRadius: ps(12),
  },
  aiCreditsContent: {
    paddingHorizontal: ps(14),
    paddingVertical: ps(10),
    alignItems: "flex-start",
    justifyContent: "center",
  },
  aiCreditsTitle: {
    fontSize: ps(14),
    fontWeight: "800",
    color: "#2B3E62",
    marginLeft: ps(1),
    marginBottom: ps(2),
    letterSpacing: -0.2,
  },
  aiCreditsSub: {
    fontSize: ps(10),
    color: "#5C6478",
    marginLeft: ps(1),
    marginBottom: ps(8),
  },
  aiCreditsBtn: {
    backgroundColor: "#C3D7FD",
    borderRadius: ps(8),
    paddingHorizontal: ps(10),
    paddingVertical: ps(6),
    flexDirection: "row",
    alignItems: "center",
  },
  aiCreditsBtnText: {
    fontSize: ps(12),
    fontWeight: "700",
    color: "#0F1B3D",
  },
  aiCreditsBtnArrow: {
    fontSize: ps(15),
    fontWeight: "700",
    color: "#0F1B3D",
    marginLeft: ps(5),
    includeFontPadding: false,
    textAlignVertical: "center",
  },
  aiCreditsClose: {
    position: "absolute",
    top: ps(-2),
    right: ps(2),
    zIndex: 10,
    width: ps(18),
    height: ps(18),
    borderRadius: ps(9),
    backgroundColor: "rgba(15,27,61,0.85)",
    alignItems: "center",
    justifyContent: "center",
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  noCreditsSheet: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    marginHorizontal: 24,
    paddingHorizontal: 28,
    paddingTop: 28,
    alignItems: "center",
  },
  noCreditsTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1A1A1A",
    marginBottom: 10,
    textAlign: "center",
  },
  noCreditsSubtitle: {
    fontSize: 14,
    color: "#666",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 20,
  },
  noCreditsBtn: {
    width: "100%",
    borderRadius: 12,
    overflow: "hidden",
    marginBottom: 10,
  },
  noCreditsBtnGradient: {
    paddingVertical: 14,
    alignItems: "center",
  },
  noCreditsBtnText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "700",
  },
  noCreditsDismiss: {
    paddingVertical: 10,
  },
  noCreditsDismissText: {
    fontSize: 14,
    color: "#888",
  },
  // ── Daily Gym Pass Section ──
  dailyPassSection: {
    backgroundColor: "#FFF8F8",
    paddingTop: 14,
    paddingBottom: 10,
    marginTop: 14,
    marginBottom: 14,
    marginHorizontal: 14,
    elevation: 2,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    borderRadius: 14,
  },
  dailyPassHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    marginBottom: 12,
    paddingVertical: 16,
  },
  dailyPassHeadingImg: {
    width: 180,
    height: 50,
  },
  dailyPassSeeAll: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
  },
  dailyPassSeeAllText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FF5757",
  },
  dailyPassScrollContent: {
    paddingHorizontal: 14,
    paddingBottom: 6,
    gap: 12,
  },
  dailyPassCardShadow: {
    borderRadius: 14,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    backgroundColor: "#fff",
  },
  dailyPassCard: {
    width: 140,
    borderRadius: 14,
    overflow: "hidden",
    backgroundColor: "#fff",
  },
  dailyPassImageWrap: {
    height: 110,
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
    overflow: "hidden",
  },
  dailyPassImage: {
    width: "100%",
    height: "100%",
  },
  dailyPassImageOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: "100%",
    justifyContent: "flex-end",
    alignItems: "center",
    paddingBottom: 6,
  },
  dailyPassPrevBookedRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  dailyPassStarCircle: {
    width: 12,
    height: 12,
    borderRadius: 8,
    backgroundColor: "#FDC700",
    alignItems: "center",
    justifyContent: "center",
  },
  dailyPassPrevBooked: {
    fontSize: 10,
    fontWeight: "700",
    color: "#FDC700",
    letterSpacing: 0.2,
  },
  dailyPassInfo: {
    paddingHorizontal: 8,
    paddingTop: 8,
    paddingBottom: 4,
  },
  dailyPassGymName: {
    fontSize: 12,
    fontWeight: "700",
    color: "#0A0A0A",
    marginBottom: 4,
  },
  dailyPassGymLocation: {
    fontSize: 11,
    color: "#62748E",
    marginBottom: 6,
  },
  dailyPassDistanceRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  dailyPassDistance: {
    fontSize: 11,
    color: "#FF5757",
    fontWeight: "500",
  },
  dailyPassBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 8,
    marginTop: 6,
    marginBottom: 10,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: "#FF5757",
    backgroundColor: "#FF5757",
    gap: 4,
  },
  dailyPassBtnText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  dailyPassTagline: {
    textAlign: "center",
    fontSize: 12,
    fontWeight: "600",
    color: "#000000",
    marginTop: 8,
    letterSpacing: 0.6,
  },
  // ── Membership Pass Section (daily-pass style) ──
  memPassSection: {
    backgroundColor: "#FFF6F3",
    paddingTop: 14,
    paddingBottom: 10,
    marginTop: 32,
  },
  memPassHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    marginBottom: 12,
    paddingVertical: 16,
  },
  memPassHeadingImg: {
    width: 180,
    height: 50,
  },
  memPassSeeAll: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
  },
  memPassSeeAllText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FF561D",
  },
  memPassScrollContent: {
    paddingHorizontal: 14,
    paddingBottom: 6,
    gap: 12,
  },
  memPassCardShadow: {
    borderRadius: 14,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    backgroundColor: "#fff",
  },
  memPassCard: {
    width: 140,
    borderRadius: 14,
    overflow: "hidden",
    backgroundColor: "#fff",
  },
  memPassImageWrap: {
    height: 110,
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
    overflow: "hidden",
  },
  memPassImage: {
    width: "100%",
    height: "100%",
  },
  memPassInfo: {
    paddingHorizontal: 8,
    paddingTop: 8,
    paddingBottom: 4,
  },
  memPassGymName: {
    fontSize: 12,
    fontWeight: "700",
    color: "#0A0A0A",
    marginBottom: 4,
  },
  memPassGymLocation: {
    fontSize: 11,
    color: "#62748E",
    marginBottom: 6,
  },
  memPassDistanceRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  memPassDistance: {
    fontSize: 11,
    color: "#FF561D",
    fontWeight: "500",
  },
  memPassBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 8,
    marginTop: 6,
    marginBottom: 4,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: "#FF561D",
    backgroundColor: "#FF561D",
    gap: 4,
  },
  memPassBtnText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  memPassPlanLabel: {
    textAlign: "center",
    fontSize: 10,
    fontWeight: "500",
    color: "#62748E",
    marginBottom: 10,
  },
  memPassTagline: {
    textAlign: "center",
    fontSize: 12,
    fontWeight: "600",
    color: "#FF561D",
    marginTop: 8,
    letterSpacing: 0.6,
  },
  // ── Section wrapper ──
  section: {
    paddingHorizontal: 10,
    paddingTop: 32,
    backgroundColor: "#ffffff",
  },
  sectionHeadingRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 14,
  },
  sectionHeadingLine: {
    flex: 1,
    height: 1,
    backgroundColor: "#E0E0E0",
  },
  sectionHeading: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1A1A1A",
    textAlign: "center",
    marginBottom: 0,
    marginHorizontal: 10,
  },
  // ── Trending Classes Timer banner ──
  trendingTimerBanner: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 0,
    marginBottom: 14,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 12,
  },
  trendingTimerFire: {
    fontSize: 14,
    marginRight: 4,
  },
  trendingTimerLabel: {
    flex: 1,
    fontSize: 12,
    fontWeight: "700",
    color: "#FFFFFF",
    letterSpacing: 0.2,
  },
  trendingTimerDigits: {
    fontSize: 16,
    color: "#FFFFFF",
    fontFamily: Platform.OS === "android" ? "AdvancedDotDigital" : undefined,
    fontWeight: Platform.OS === "ios" ? "700" : "400",
    fontVariant: ["tabular-nums"],
    letterSpacing: 1.5,
    marginLeft: 10,
  },
  // ── Book Fitness row ──
  bookRow: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 12,
  },
  bookCard: {
    width: bookCardWidth,
    borderRadius: 12,
    backgroundColor: "#fff",
    overflow: "hidden",
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    borderWidth: Platform.OS === "ios" ? 1 : 0,
    borderColor: "#eee",
  },
  bookCardImage: {
    width: "100%",
    height: isTablet ? 180 : bookCardWidth * 0.9,
  },
  bookCardMeta: {
    padding: 8,
    paddingBottom: 10,
  },
  bookCardTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  bookCardTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#1A1A1A",
    flex: 1,
    marginRight: 3,
  },
  priceRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 3,
  },
  priceText: {
    fontSize: 11,
    color: "#555",
  },
  bookCardSub: {
    fontSize: 10,
    color: "#888",
    lineHeight: 14,
    textAlign: "left",
  },
  //--Gym Mate Section--//
  gymMateSection: {
    marginTop: 20,
  },
  // ── Friend Requests Banner ──
  friendReqBanner: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F2F2F2",
    marginHorizontal: 14,
    marginTop: 14,
    borderRadius: 40,
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  friendReqAvatars: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 10,
  },
  friendReqAvatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 2,
    borderColor: "#fff",
  },
  friendReqText: {
    flexShrink: 1,
    fontSize: 13,
    fontWeight: "600",
    color: "#1A1A1A",
  },
  friendReqTextWrap: {
    flexShrink: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  friendReqCount: {
    fontWeight: "800",
  },
  gmCard: {
    width: GM_CARD_W,
    height: 360,
    borderRadius: 18,
    overflow: "hidden",
    backgroundColor: "#1A1A1A",
  },
  gmCardImage: {
    width: "100%",
    height: "100%",
    position: "absolute",
  },
  gmCardOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 18,
    paddingBottom: 20,
    paddingTop: 50,
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
  },
  gmCardName: {
    fontSize: 20,
    fontWeight: "800",
    color: "#FFF",
    marginBottom: 4,
  },
  gmCardInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 3,
  },
  gmCardInfoText: {
    fontSize: 12,
    color: "rgba(255,255,255,0.85)",
    fontWeight: "700",
    flex: 1,
  },
  gmCardBtn: {
    marginTop: 12,
    backgroundColor: "rgba(255,255,255,0.4)",
    borderRadius: 30,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.4)",
  },
  gmCardBtnText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  gmCardBtnSent: {
    backgroundColor: "rgba(16,185,80,0.55)",
    borderColor: "rgba(255,255,255,0.6)",
  },
  gmDotRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 12,
    gap: 6,
  },
  gmDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: "#D3D3D3",
  },
  gmDotActive: {
    width: 18,
    height: 7,
    backgroundColor: "#FF5757",
  },
  // Onboarding CTA
  gmOnboardCta: {
    marginHorizontal: 16,
    borderRadius: 16,
    padding: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#FFE0D6",
  },
  gmOnboardTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    marginBottom: 14,
  },
  gmOnboardIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#FFF0EB",
    alignItems: "center",
    justifyContent: "center",
  },
  gmOnboardTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: "#1A1A1A",
    marginBottom: 4,
  },
  gmOnboardSub: {
    fontSize: 12,
    color: "#6B7280",
    lineHeight: 17,
  },
  gmOnboardBtnRow: {
    alignItems: "center",
  },
  gmOnboardBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FF5757",
    borderRadius: 10,
    paddingVertical: 11,
    paddingHorizontal: 24,
    gap: 6,
    alignSelf: "stretch",
  },
  gmOnboardBtnText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#FFF",
  },
  gmOnboardFootnote: {
    fontSize: 10.5,
    color: "#9CA3AF",
    marginTop: 6,
  },
  // ── Membership / Fitness Classes section ──
  membershipSection: {
    paddingBottom: 20,
    marginTop: 20,
    backgroundColor: "#ffffff",
  },
  membershipHeadingCard: {
    paddingVertical: 8,
    paddingHorizontal: 10,
    marginBottom: 14,
  },
  viewAll: {
    fontSize: 13,
    color: "#007AFF",
    fontWeight: "500",
  },
  membershipRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  membershipCard: {
    flex: 1,
    borderRadius: 10,
    overflow: "hidden",
    backgroundColor: "#000",
    position: "relative",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.07,
    shadowRadius: 4,
  },
  membershipCardImage: {
    width: "100%",
    aspectRatio: 1,
  },
  membershipCardOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "rgba(0,0,0,0.45)",
    paddingVertical: 7,
    paddingHorizontal: 8,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  },
  membershipCardLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "#fff",
    textAlign: "center",
  },
  viewAllBtn: {
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 4,
  },
  viewAllInner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
  },
  // ── Membership Gym Cards (horizontal scroll) ──
  memGymScrollContent: {
    paddingHorizontal: 14,
    paddingBottom: 6,
    gap: 12,
  },
  memGymCardShadow: {
    borderRadius: 14,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    backgroundColor: "#fff",
  },
  memGymCard: {
    width: 240,
    borderRadius: 14,
    overflow: "hidden",
    backgroundColor: "#fff",
  },
  memGymImageWrap: {
    height: 130,
    position: "relative",
    overflow: "hidden",
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
  },
  memGymImage: {
    width: "100%",
    height: "100%",
  },
  memGymImageCurve: {
    position: "absolute",
    bottom: -14,
    left: -0,
    right: -0,
    height: 26,
    backgroundColor: "#fff",
    borderTopLeftRadius: 100,
    borderTopRightRadius: 100,
  },
  memGymTrendingBadge: {
    position: "absolute",
    top: 10,
    left: 10,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#000",
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
    overflow: "hidden",
  },
  memGymTrendingText: {
    fontSize: 11,
    fontWeight: "700",
    marginLeft: 3,
    zIndex: 1,
  },
  memGymInfo: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 10,
    paddingTop: 6,
    paddingBottom: 3,
  },
  memGymName: {
    fontSize: 13,
    fontWeight: "700",
    color: "#0A0A0A",
    marginBottom: 3,
  },
  memGymLocationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    marginBottom: 8,
  },
  memGymLocation: {
    fontSize: 11,
    color: "#4A5565",
    fontWeight: "400",
  },
  memGymPriceBadge: {
    flexDirection: "row",
    alignItems: "baseline",
    backgroundColor: "#FF5757",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    alignSelf: "flex-start",
  },
  memGymPriceRupee: {
    fontSize: 11,
    color: "#fff",
    fontWeight: "700",
  },
  memGymPriceAmount: {
    fontSize: 14,
    color: "#fff",
    fontWeight: "800",
  },
  memGymPriceUnit: {
    fontSize: 9,
    color: "#fddfdf",
    fontWeight: "500",
    marginLeft: 1,
  },
  memGymFooter: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
    borderBottomLeftRadius: 14,
    borderBottomRightRadius: 14,
  },
  memGymFooterText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#5E2F00",
    letterSpacing: 0.1,
  },
  // ── Feature cards (Nutrition & Scanner) ──
  featureCard: {
    height: 130,
    borderRadius: 14,
    overflow: "visible",
    paddingTop: 20,
    position: "relative",
    marginBottom: 5,
  },
  featureCardInner: {
    flexDirection: "row",
    alignItems: "center",
    height: "100%",
    borderRadius: 14,
    backgroundColor: "#fff",
    paddingHorizontal: 14,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
  },
  featureCardLeft: {
    maxWidth: "65%",
    justifyContent: "center",
  },
  featureCardTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1A1A1A",
    marginBottom: 4,
    lineHeight: 20,
  },
  featureCardSub: {
    fontSize: 11,
    color: "#777",
    lineHeight: 16,
    marginBottom: 10,
  },
  featureBtnShadow: {
    borderRadius: 8,
    alignSelf: "flex-start",
    elevation: 4,
    shadowColor: "#000000",
    shadowOffset: { width: 5.9, height: 5.9 },
    shadowOpacity: 0.192,
    shadowRadius: 4.35,
  },
  featureBtn: {
    backgroundColor: "#FF5757",
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 14,
    alignSelf: "flex-start",
  },
  scanBtn: {
    backgroundColor: "#FF5757",
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 10,
  },
  featureBtnText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#fff",
  },
  featureCardImageContainer: {
    position: "absolute",
    right: 0,
    bottom: 0,
    zIndex: 10,
  },
  featureCardImage: {
    width: featureImageSize,
    height: featureImageSize * 1.2,
  },
  // ── Promo cards (Nutrition & Scanner) ──
  promoCard: {
    flexDirection: "row",
    borderRadius: 14,
    backgroundColor: "#fff",
    overflow: "hidden",
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    marginBottom: 4,
    minHeight: 110,
    borderWidth: Platform.OS === "ios" ? 1 : 0,
    borderColor: "#eee",
  },
  promoCardLeft: {
    flex: 1,
    padding: 16,
    paddingRight: 10,
    justifyContent: "center",
    paddingVertical: 10,
  },
  promoCardTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1A1A1A",
    marginBottom: 2,
    lineHeight: 21,
  },
  promoCardSub: {
    fontSize: 11,
    color: "#777",
    lineHeight: 17,
    marginBottom: 0,
  },
  promoCardSubBelow: {
    color: "rgba(0,0,0,0.8)",
    fontSize: 11,
    marginBottom: 8,
    fontWeight: 500,
  },
  promoCardImageWrap: {
    width: width * 0.42,
    justifyContent: "flex-end",
    alignItems: "flex-end",
    overflow: "hidden",
  },
  promoCardImageWrapMobile: {
    width: width * 0.33,
    justifyContent: "flex-end",
    alignItems: "flex-end",
    overflow: "hidden",
  },
  promoCardImage: {
    width: 146,
    height: 146,
  },
  promoCardImageMobile: {
    width: 120,
    height: 120,
  },
  // ── Nutrition Card ──
  nutriCard: {
    borderRadius: 14,
    overflow: "hidden",
    backgroundColor: "#FFFFFF",
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    marginBottom: 4,
    borderWidth: Platform.OS === "ios" ? 1 : 0,
    borderColor: "#ddd",
  },
  nutriCardHeader: {
    backgroundColor: "#F4FAFF",
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 10,
    marginBottom: 14,
    alignItems: "center",
  },
  nutriCardHeaderText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1A1A1A",
    textAlign: "center",
  },
  nutriCardBody: {
    backgroundColor: "#F4FAFF",
    marginHorizontal: 12,
    borderRadius: 12,
    padding: 12,
    alignItems: "flex-start",
    borderWidth: 1,
    borderColor: "#D9ECFF",
    paddingHorizontal: 8,
    paddingBottom: 4,
    overflow: "visible",
  },
  nutriLimitedBadgePos: {
    position: "absolute",
    top: -12,
    right: -4,
    zIndex: 10,
  },
  nutriLimitedBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    overflow: "hidden",
  },
  nutriLimitedBadgeText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  nutriPriceCard: {
    backgroundColor: "#F4FAFF",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#D9ECFF",
    paddingHorizontal: 20,
    paddingTop: 6,
    paddingBottom: 10,
    alignItems: "center",
    width: "90%",
    overflow: "visible",
    marginTop: 6,
  },
  nutriSaveBadge: {
    position: "absolute",
    top: 0,
    right: 0,
    backgroundColor: "#2B9E55",
    borderBottomLeftRadius: 20,
    borderTopRightRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
    zIndex: 10,
  },
  nutriSaveBadgeText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "700",
  },
  nutriCardBodyLeft: {
    width: "60%",
    paddingRight: 8,
  },
  nutriCardBodyTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#1A1A1A",
    marginBottom: 2,
    marginLeft: 0,
  },
  nutriBulletRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 2,
  },
  nutriBulletDot: {
    fontSize: 12,
    color: "#555",
    marginRight: 4,
    lineHeight: 18,
  },
  nutriBulletText: {
    fontSize: 12,
    color: "#555",
    lineHeight: 18,
  },
  nutriCardBodyRight: {
    width: "40%",
  },
  nutriCardImage: {
    width: 140,
    height: 120,
    marginBottom: -6,
  },
  nutriCardFooter: {
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 14,
    alignItems: "center",
    overflow: "visible",
  },
  nutriBatchText: {
    fontSize: 12,
    color: "#444",
    marginBottom: 4,
    textAlign: "center",
  },
  nutriSpotsText: {
    color: "#E53935",
    fontWeight: "600",
  },
  nutriPriceRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  nutriPrice: {
    fontSize: 26,
    fontWeight: "800",
    color: "#1A1A1A",
  },
  nutriPriceOld: {
    fontSize: 14,
    color: "#999",
    textDecorationLine: "line-through",
    marginLeft: 6,
    alignSelf: "flex-end",
    marginBottom: 2,
  },
  nutriBtn: {
    backgroundColor: "#FF5757",
    borderRadius: 30,
    paddingVertical: 8,
    paddingHorizontal: 20,
    alignItems: "center",
    width: "75%",
  },
  nutriBtnText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "700",
  },
  nutriTrustedText: {
    fontSize: 12,
    fontWeight: "bold",
  },
  // ── Diet Plans Section Heading ──
  dietPlansHeader: {
    marginTop: ps(32),
    marginBottom: ps(15),
  },
  // ── Talk to Expert (₹199) Card ──
  expertCardWrap: {
    marginHorizontal: 12,
    marginTop: 8,
    borderRadius: 14,
    overflow: "hidden",
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    backgroundColor: "#fff",
  },
  expertCardImg: {
    width: "100%",
    aspectRatio: 670 / 440,
    borderRadius: 14,
  },
  // ── Location Header ──
  locationHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#C7DAFF",
    paddingHorizontal: 14,
    paddingBottom: 15,
    paddingTop: 8,
  },
  locationLeft: {
    flex: 1,
    flexDirection: "row",
    alignItems: "flex-start",
    marginRight: 10,
    minWidth: 0,
  },
  locationArea: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1A1A1A",
    lineHeight: 20,
  },
  locationAddressText: {
    fontSize: 11,
    color: "#666",
    lineHeight: 15,
    marginTop: 1,
  },
  locationAreaDenied: {
    color: "#4A4A4A",
    fontWeight: "600",
  },
  locationEnableRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 1,
  },
  locationEnableText: {
    fontSize: 11,
    color: "#FF5757",
    fontWeight: "600",
    lineHeight: 15,
  },
  locationRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  earnBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#C7DAFF",
    borderWidth: 1,
    borderColor: "#eee",
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 6,
    gap: 5,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    position: "relative",
  },
  sparkleIcon: {
    position: "absolute",
    top: -10,
    right: 10,
  },
  earnIcon: {
    width: 22,
    height: 22,
  },
  earnLabel: {
    fontSize: 10,
    color: "#525252",
    lineHeight: 13,
  },
  earnAmount: {
    fontSize: 12,
    fontWeight: "700",
    color: "#191919",
    lineHeight: 15,
  },
  avatarBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#C7DAFF",
    alignItems: "center",
    justifyContent: "center",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    borderWidth: 1,
    borderColor: "#94AEE0",
  },
  // ── Section title row with inline View all ──
  sectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionTitleText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1A1A1A",
  },
  viewAllInline: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    paddingLeft: 16,
  },
  // ── Trending Workouts cards ──
  marqueeContainer: {
    overflow: "hidden",
    paddingBottom: 8,
  },
  marqueeRow: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  trendingCardShadow: {
    width: (width - 30) / 2,
    borderRadius: 14,
  },
  trendingCard: {
    width: "100%",
    borderRadius: 14,
    overflow: "hidden",
  },
  trendingCardBg: {
    width: "100%",
    height: Math.round(((width - 32 - 10) / 2) * 0.7),
    justifyContent: "space-between",
  },
  trendingCardTop: {
    zIndex: 1,
    paddingTop: 10,
    paddingLeft: 10,
  },
  trendingCardTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: "#000000",
    marginBottom: 2,
  },
  trendingCardSlots: {
    fontSize: 11,
    color: "rgba(0,0,0,0.85)",
  },
  trendingCardBottom: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    zIndex: 1,
    paddingBottom: 10,
    paddingLeft: 10,
    paddingRight: 10,
  },
  trendingStartAt: {
    fontSize: 11,
    color: "rgba(0,0,0,0.85)",
    marginBottom: 2,
  },
  trendingTimeRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  trendingTime: {
    fontSize: 12,
    fontWeight: "700",
    color: "#FF5757",
  },
  trendingPriceText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#FF5757",
  },
  categoryPillRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 12,
    marginHorizontal: 12,
  },
  categoryPill: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    paddingVertical: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
  },
  categoryPillText: {
    fontSize: 12,
    fontWeight: "500",
    color: "#1A1A1A",
  },
  categoryPillViewAll: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#2564eb7c",
    borderRadius: 8,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    backgroundColor: "#fff",
  },
  categoryPillViewAllText: {
    fontSize: 13,
    fontWeight: "500",
    color: "#2563EB",
  },
  freeBadge: {
    backgroundColor: "#22C55E",
    borderRadius: 4,
    paddingHorizontal: 7,
    paddingVertical: 2,
    alignSelf: "flex-start",
    marginBottom: 6,
  },
  freeBadgeText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#fff",
  },
  // ── Skeleton ──
  skeletonBox: {
    backgroundColor: "#E0E0E0",
    borderRadius: 8,
    opacity: 0.6,
  },
  // ── Location header ──
  locationAreaRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  locationIcon: {
    marginTop: 1,
    marginRight: 4,
  },
  locationChevron: {
    marginLeft: 4,
    marginTop: 4,
  },
  // ── Trending cards ──
  trendingTimeIcon: {
    marginRight: 3,
  },
  trendingPricePill: {
    borderWidth: 1,
    borderColor: "#FF5757",
    backgroundColor: "#FFF",
    paddingHorizontal: 6,
    borderRadius: 4,
    paddingVertical: 2,
  },
  // ── Nutrition card ──
  nutriBodyRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  nutriTrustedRow: {
    marginTop: 6,
    flexDirection: "row",
    alignItems: "center",
  },
  nutriCallBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#FF5757",
    borderRadius: 30,
    paddingVertical: 8,
    paddingHorizontal: 24,
    marginTop: 10,
  },
  nutriCallBtnText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "700",
  },
  joinModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.55)",
    justifyContent: "center",
    alignItems: "center",
  },
  // ── Daily Pass Promo Modal ──
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "flex-end",
  },
  modalCard: {
    width: "100%",
    backgroundColor: "#E2F4FD",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 80,
    alignItems: "center",
  },
  modalImageWrap: {
    position: "absolute",
    top: -70,
    left: 0,
    right: 0,
    alignItems: "center",
    zIndex: 10,
  },
  modalCardsImage: {
    width: 220,
    height: 150,
  },
  modalClose: {
    position: "absolute",
    top: 16,
    right: 16,
    zIndex: 20,
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 4,
  },
  modalBody: {
    width: "100%",
    paddingHorizontal: 20,
    alignItems: "center",
  },
  modalDemandRow: {
    marginBottom: 16,
  },
  modalDemandText: {
    marginTop: 10,
    fontSize: 14,
    fontWeight: "600",
    color: "#1a1a2e",
  },
  modalTodayCard: {
    width: "100%",
    backgroundColor: "rgba(255,255,255,0.3)",
    borderRadius: 16,
    paddingVertical: 8,
    paddingHorizontal: 20,
    alignItems: "center",
    marginBottom: 12,
  },
  modalTodayLabel: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1a1a2e",
    marginBottom: 10,
  },
  modalPricePill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "rgba(19,100,215,0.05)",
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 24,
  },
  modalSalePrice: {
    fontSize: 24,
    fontWeight: "800",
    color: "#000",
  },
  modalOriginalPrice: {
    fontSize: 18,
    fontWeight: "500",
    color: "#999",
    textDecorationLine: "line-through",
  },
  modalTerms: {
    fontSize: 12,
    color: "#000000",
    marginBottom: 20,
  },
  modalCta: {
    width: width - 40,
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: "center",
  },
  modalCtaText: {
    fontSize: 16,
    fontWeight: "800",
    color: "#fff",
    letterSpacing: 0.3,
  },
  // ── Refer a Friend Modal ──
  referModalCard: {
    width: "100%",
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 20,
    alignItems: "center",
  },
  referModalBody: {
    width: "100%",
    paddingHorizontal: 24,
    alignItems: "center",
  },
  referModalImage: {
    width: 180,
    height: 180,
    alignSelf: "center",
    marginBottom: 4,
  },
  referModalTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1a1a1a",
    textAlign: "center",
  },
  referModalReward: {
    fontSize: 26,
    fontWeight: "800",
    color: "#E6A800",
    textAlign: "center",
    marginTop: 4,
  },
  referModalDesc: {
    fontSize: 13,
    color: "#666",
    textAlign: "center",
    lineHeight: 20,
    marginTop: 6,
    marginBottom: 22,
  },
  referWhatsappButton: {
    width: "100%",
    borderRadius: 10,
    overflow: "hidden",
  },
  referWhatsappGradient: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    gap: 10,
    borderRadius: 10,
  },
  referWhatsappText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "700",
  },
  rewardCtaButton: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: "#FFF7E0",
    borderWidth: 1,
    borderColor: "#F3DFA2",
  },
  rewardCtaText: {
    color: "#B8860B",
    fontSize: 15,
    fontWeight: "700",
  },
  promoCtaButton: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: "#1364D7",
  },
  promoCtaText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "700",
  },
  // ── Nutrition Status Cards (purchased states) ──
  nutriStatusCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 18,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    borderWidth: 1,
    borderColor: "#EEF0F4",
    paddingBottom: 6,
    marginBottom: 10,
  },
  nutriStatusHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  nutriStatusIcon: {
    width: 22,
    height: 22,
    marginRight: 8,
  },
  nutriStatusTitle: {
    fontSize: 13,
    fontWeight: "600",
    color: "#444",
  },
  nutriStatusDateRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  nutriStatusDate: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1A1A1A",
  },
  nutriStatusSub: {
    fontSize: 13,
    color: "#666",
    marginBottom: 10,
  },
  nutriJoinBtn: {
    backgroundColor: "#007AFF",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
  },
  nutriJoinBtnText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#fff",
  },
  joinModalContent: {
    width: "85%",
    backgroundColor: "#FFF",
    borderRadius: 16,
    padding: 24,
    alignItems: "center",
    elevation: 8,
  },
  joinModalIconWrap: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: "#EEF6FF",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  joinModalTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1A1A1A",
    marginBottom: 8,
    textAlign: "center",
  },
  joinModalMessage: {
    fontSize: 14,
    color: "#666",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 16,
  },
  joinModalTimeBox: {
    backgroundColor: "#F5F7FA",
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
    width: "100%",
    marginBottom: 20,
    gap: 4,
  },
  joinModalTimeText: {
    fontSize: 13,
    color: "#444",
    textAlign: "center",
  },
  joinModalCloseBtn: {
    backgroundColor: "#007AFF",
    borderRadius: 12,
    paddingVertical: 13,
    paddingHorizontal: 40,
    alignItems: "center",
    width: "100%",
  },
  joinModalCloseBtnText: {
    color: "#FFF",
    fontSize: 15,
    fontWeight: "700",
  },
  nutriPlanInProgressTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1A1A1A",
    lineHeight: 22,
    marginBottom: 6,
  },
  nutriProgressBarBg: {
    height: 8,
    backgroundColor: "#E8EDF5",
    borderRadius: 4,
    overflow: "hidden",
    marginVertical: 4,
  },
  nutriProgressBarFill: {
    width: "60%",
    height: "100%",
    backgroundColor: "#007AFF",
    borderRadius: 4,
  },
  nutriViewPlanBtn: {
    backgroundColor: "#28A745",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
  },
  nutriViewPlanBtnText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#fff",
  },
  dietPlanRowCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginVertical: 12,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    borderWidth: 1,
    borderColor: "#EEF0F4",
  },
  dietPlanRowIcon: {
    width: 22,
    height: 22,
    marginRight: 10,
  },
  dietPlanRowText: {
    flex: 1,
    fontSize: 14,
    fontWeight: "600",
    color: "#1A1A1A",
  },
  dietPlanRowArrow: {
    fontSize: 22,
    color: "#28A745",
    fontWeight: "700",
    marginLeft: 8,
  },
  // ── Reward Program Postponement Card ──
  rewardPostponeCard: {
    marginHorizontal: 8,
    marginTop: 12,
    marginBottom: 4,
    borderRadius: 18,
    overflow: Platform.OS === "android" ? "hidden" : "visible",
    elevation: 3,
    shadowColor: "#C89B3C",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
  },
  rewardPostponeGradient: {
    borderRadius: 18,
    paddingHorizontal: 10,
    paddingTop: 14,
    paddingBottom: 14,
    overflow: "hidden",
  },
  rewardPostponeClose: {
    position: "absolute",
    top: 10,
    right: 12,
    zIndex: 10,
    backgroundColor: "rgba(139,105,20,0.1)",
    borderRadius: 20,
    padding: 4,
  },
  rewardPostponeRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  rewardPostponeImage: {
    width: 60,
    height: 75,
    marginRight: 10,
  },
  rewardPostponeTextCol: {
    flex: 1,
  },
  rewardPostponeTag: {
    fontSize: 9,
    fontWeight: "800",
    color: "#8B6914",
    letterSpacing: 1,
    textTransform: "uppercase",
    backgroundColor: "rgba(139,105,20,0.12)",
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 10,
    overflow: "hidden",
    alignSelf: "flex-start",
    marginBottom: 3,
  },
  rewardPostponeTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: "#5C4500",
    marginBottom: 3,
  },
  rewardPostponeSub: {
    fontSize: 11,
    color: "#7A6320",
    lineHeight: 15,
    marginBottom: 8,
  },
  rewardPostponePill: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "rgba(139,105,20,0.1)",
    borderRadius: 20,
    paddingVertical: 5,
    paddingHorizontal: 12,
    gap: 4,
  },
  rewardPostponePillText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#8B6914",
  },
  // ── Reward Update Detail Modal ──
  rewardUpdateSheet: {
    width: "100%",
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 20,
    maxHeight: "80%",
  },
  rewardUpdateScroll: {
    paddingHorizontal: 24,
  },
  rewardUpdateEmoji: {
    fontSize: 32,
    textAlign: "center",
    marginBottom: 4,
  },
  rewardUpdateHeading: {
    fontSize: 18,
    fontWeight: "900",
    color: "#1a1a1a",
    textAlign: "center",
    letterSpacing: 0.5,
    marginBottom: 16,
  },
  rewardUpdateBody: {
    fontSize: 14,
    color: "#444",
    lineHeight: 21,
    marginBottom: 10,
  },
  rewardUpdateHighlight: {
    backgroundColor: "#FFF8E1",
    borderRadius: 12,
    padding: 14,
    marginVertical: 12,
    borderLeftWidth: 4,
    borderLeftColor: "#E6B136",
  },
  rewardUpdateHighlightText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#5C4500",
    lineHeight: 22,
  },
  rewardRegisterBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#D89319",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginVertical: 12,
    marginTop: 0,
    gap: 10,
  },
  rewardRegisterBtnText: {
    flex: 1,
    fontSize: 13,
    fontWeight: "700",
    color: "#fff",
    lineHeight: 18,
  },
  rewardRegisteredCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#E8F5E9",
    borderRadius: 12,
    borderLeftWidth: 4,
    borderLeftColor: "#4CAF50",
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginVertical: 12,
    gap: 10,
  },
  rewardRegisteredText: {
    flex: 1,
    fontSize: 13,
    fontWeight: "600",
    color: "#2E7D32",
    lineHeight: 18,
  },
  rewardUpdateSubhead: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1a1a1a",
    marginBottom: 8,
  },
  rewardUpdateCheck: {
    fontSize: 14,
    color: "#333",
    lineHeight: 24,
    marginLeft: 4,
  },
  rewardUpdateCta: {
    marginTop: 20,
    marginBottom: 8,
    borderRadius: 12,
    overflow: "hidden",
  },
  rewardUpdateCtaGradient: {
    paddingVertical: 14,
    alignItems: "center",
    borderRadius: 12,
  },
  rewardUpdateCtaText: {
    fontSize: 15,
    fontWeight: "800",
    color: "#fff",
    letterSpacing: 0.3,
  },
  // ── Workout Partners Section ──
  wpSection: {
    paddingHorizontal: 10,
    paddingTop: 32,
    paddingBottom: 16,
    backgroundColor: "#ffffff",
  },
  wpScrollContent: {
    paddingHorizontal: 14,
    gap: 12,
  },
  wpCardShadow: {
    borderRadius: 16,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    backgroundColor: "#1A1A1A",
  },
  wpCard: {
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: "#1A1A1A",
  },
  wpCardImage: {
    width: "100%",
    height: "100%",
    position: "absolute",
  },
  wpCardPlaceholder: {
    width: "100%",
    height: "100%",
    position: "absolute",
    backgroundColor: "#2A2A2A",
    alignItems: "center",
    justifyContent: "center",
    paddingBottom: 50,
  },
  wpCardOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 12,
    paddingBottom: 14,
    paddingTop: 50,
  },
  wpMatchBadge: {
    position: "absolute",
    top: 10,
    right: 10,
    zIndex: 5,
    backgroundColor: "#05DF72",
    borderRadius: 20,
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  wpMatchText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#FFF",
  },
  wpCardName: {
    fontSize: 15,
    fontWeight: "800",
    color: "#FFF",
    marginBottom: 3,
  },
  wpCardBio: {
    fontSize: 11,
    color: "rgba(255,255,255,0.75)",
    lineHeight: 15,
    marginBottom: 8,
  },
  wpTagRow: {
    flexDirection: "row",
    flexWrap: "nowrap",
    alignItems: "center",
    gap: 4,
    marginBottom: 8,
  },
  wpTag: {
    backgroundColor: "rgba(255,255,255,0.18)",
    borderRadius: 10,
    paddingHorizontal: 7,
    paddingVertical: 3,
  },
  wpTagText: {
    fontSize: 9.5,
    fontWeight: "600",
    color: "rgba(255,255,255,0.9)",
  },
  wpAddBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    backgroundColor: "rgba(255,255,255,0.25)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.35)",
    borderRadius: 24,
    paddingVertical: 7,
  },
  wpAddBtnText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#FFF",
  },
  // ── Frequently Booked Card ──
  freqBookedWrap: {
    paddingHorizontal: 14,
    marginTop: 14,
    marginBottom: 20,
  },
  freqBookedHeading: {
    paddingVertical: 8,
    paddingHorizontal: 10,
    marginHorizontal: -10,
    marginBottom: 10,
  },
  freqBookedCard: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderRadius: 14,
    overflow: "hidden",
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    borderWidth: Platform.OS === "ios" ? 1 : 0,
    borderColor: "#EEF0F4",
  },
  freqBookedImageWrap: {
    width: 120,
  },
  freqBookedImage: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  freqBookedImageFade: {
    position: "absolute",
    right: 0,
    top: 0,
    bottom: 0,
    width: 20,
  },
  freqBookedContent: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    justifyContent: "center",
  },
  freqBookedGymName: {
    fontSize: 14,
    fontWeight: "700",
    color: "#0A0A0A",
    marginBottom: 4,
    marginTop: 10,
  },
  freqBookedBadge: {
    position: "absolute",
    top: 0,
    right: 0,
    zIndex: 5,
    backgroundColor: "#FFF7ED",
    borderTopRightRadius: 6,
    borderBottomLeftRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  freqBookedBadgeText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#CA3500",
  },
  freqBookedLocationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    marginBottom: 4,
  },
  freqBookedLocationText: {
    fontSize: 12,
    color: "#4A5565",
    flex: 1,
  },
  freqBookedInfo: {
    fontSize: 11,
    color: "#000000",
    marginBottom: 8,
  },
  freqBookedBottomRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  freqBookedPrice: {
    width: "50%",
    fontSize: 14,
    fontWeight: "700",
    color: "#FF5757",
    backgroundColor: "#FFEEEE",
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 6,
    textAlign: "center",
  },
  freqBookedBtn: {
    width: "50%",
    backgroundColor: "#FF5757",
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 6,
    alignItems: "center",
  },
  freqBookedBtnText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#fff",
  },
});

export default styles;
